runtime: nodejs20
instance_class: F1

env_variables:
  NODE_ENV: "production"
  JWT_SECRET: "snapkitty_super_secure_token"
  OPENAI_API_KEY: "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"
  MONGO_URI: "mongodb+srv://snapkitty:snapkitty123456@cluster0.ygyrjtt.mongodb.net/snapkitty?retryWrites=true&w=majority"
handlers:

  - url: /favicon\.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico

  - url: /assets             
    static_dir: public/assets

  - url: /static
    static_dir: public/static

  - url: /uploads
    static_dir: uploads              

  - url: /api/.*
    script: auto

  - url: /.*
    script: auto