name: Deploy to GCP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install --prefix client && npm install --prefix server
    - name: Build frontend
      run: npm run build --prefix client
    - name: Deploy step placeholder
      run: echo 'This is where you would deploy to GCP'
